chore: UI Improvements of documentation
UPRI-earthquake/upri-earthquake.github.io pull request #1
Opened 2023-10-05 17:17 UTC by alyssapatricia

# Detailed Description

### Summary
 
> This PR creates an improved documentation: [Improved Documentation](https://alyssapatricia.github.io/ui/)

 
- Changed the theme from Jekyll to Sphinx
- Organized the Topic
- Added a Table of Contents panel
- Added a search engine
- Proofread the existing contents
- Improved overall UI

 
### Motivation & Context

- To improve the documentation of the UPRI EarthquakeHub Project

### Dependencies

- [sphinx](https://www.sphinx-doc.org/en/master/) is the documentation generator
- [sphinx_rtd_theme](https://sphinx-rtd-theme.readthedocs.io/) is the theme of the documentation. 
- [myst_parser](https://pypi.org/project/myst-parser/) is used to parse the .md files (the format which the content files were written) to make it readable by the sphinx environtment
- [sphinxcontrib-openapi](https://github.com/sphinx-contrib/openapi) to deploy API docs

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-18 04:39 UTC, chrscbs commented
Hello, Pat. I have successfully cloned your work your repository to mine. Now, I am deploying it to github pages but I have encountered some error in workflow. I have followed your instructions in the readme file. Providing here the screenshots of the error I encountered, please advice on what to do. Thanks!

2023-10-18 06:08 UTC, chrscbs requested changes

2023-10-18 06:08 UTC, chrscbs commented on README.md
> +1. Configure GitHub Pages: In your Forked GitHub repository, go to the "Settings" tab and scroll down to the "GitHub Pages" section. Set the source branch to "gh-pages" and the "docs" folder. Save th
Okay, it now works by changing the required directory to use in building the github-pages from /docs to /(root).

Please change the instruction under README. Thanks

2023-10-18 06:15 UTC, chrscbs commented
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/80037186/fbce8785-8507-4169-bf04-d1fa7f6c6380)

Whenever I click this link, this doesn't redirect to the right link. Please fix.

2023-10-18 06:30 UTC, chrscbs commented
Comments:

1. Whenever I click this link, this doesn't redirect me to the right link. Please fix this. 
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/80037186/5e41ec9b-d019-4438-bd05-3c871c41ce67)
2. Please fix this as well.
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/80037186/35448b18-2549-4919-97a6-acff28cf9132)
3. And also this one.
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/80037186/a05600c6-65f6-41da-a381-e3d962b51241)
4. Can we also do opening of clickable links in a new tab whenever a link is clicked, instead of directly redirecting through the same tab in browser. This is for all the clickable links within the documentation.
5. Page content is not occupying the whole screen. Leaving a large portion of the page blank. 
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/80037186/18e85586-6f2f-4cbf-8f06-39bc7dea6c3a)

2023-11-20 06:09 UTC, chrscbs commented
Laki ng improvement ng UI. Grabeeee! Lupet! 

Last minimal request for change; after this approve na 'tong PR for me. I also checked yung api-docs, grabe din improvement. Okay din contents. Kumpleto lahat ng endpoints.
1. This is the last request for change: 
Pakichange yung info na ito under this page: https://alyssapatricia.github.io/ui/sending-data-to-ehub-network.html
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/80037186/40d43a65-47dc-4062-b809-ba74e9687807)

2024-01-10 12:44 UTC, prokorpio commented
These need to be fixed:
1. This probably looks better in white
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/47804913/965e9454-d812-41cc-8958-f34935f74315)
2. Improve "make understanding more significant" 
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/47804913/34677680-9803-457d-92cc-3de020703427)
3. In FDSNWS tutorial, "fingerprint" is a more precise analogy than "manual"
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/47804913/ebf25320-8fcb-4a0c-9fb9-f6e3e87e373a)
4. The sender-frontend section is missing.
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/47804913/41f17035-e306-42f5-ba01-2603818bb3ad)
![image](https://github.com/UPRI-earthquake/upri-earthquake.github.io/assets/47804913/b34553a9-3878-47f8-ae5f-9b16a29eeddb)


Other than those mentioned above, this is a huge improvement for the documentation :) Plus points for the following:
1. Most of the explanation in the FDSNWS tutorial are well thought-out to fit our target audience.
2. Examples and additional links in the FDSNWS tutorial are also very effective add-ons.
3. The new figures for the topic discussions are also effective in communicating the concepts.

I will merge this now but will also create an [issue](https://github.com/UPRI-earthquake/upri-earthquake.github.io/issues/2) to address the above. Thank you.

2024-01-10 12:50 UTC, merged